// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFnpsETe3FNwJJ-5rqecU33HCdS4VKwI4',
    appId: '1:229400889372:web:549c137cebc73015ebb7d9',
    messagingSenderId: '229400889372',
    projectId: 'zing-mp3-clone-d51e7',
    authDomain: 'zing-mp3-clone-d51e7.firebaseapp.com',
    storageBucket: 'zing-mp3-clone-d51e7.firebasestorage.app',
    measurementId: 'G-DDQCWVJCJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkmR5XDS4QokEMcYrN4Y1G8ehzFU7Ok_Q',
    appId: '1:229400889372:android:decefa0222a8ac8bebb7d9',
    messagingSenderId: '229400889372',
    projectId: 'zing-mp3-clone-d51e7',
    storageBucket: 'zing-mp3-clone-d51e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDByBAWlCzqT1f7B1RCxO6VLjMDVryNDXQ',
    appId: '1:229400889372:ios:e6b94a3b55e0d870ebb7d9',
    messagingSenderId: '229400889372',
    projectId: 'zing-mp3-clone-d51e7',
    storageBucket: 'zing-mp3-clone-d51e7.firebasestorage.app',
    iosBundleId: 'com.example.mp3Clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDByBAWlCzqT1f7B1RCxO6VLjMDVryNDXQ',
    appId: '1:229400889372:ios:e6b94a3b55e0d870ebb7d9',
    messagingSenderId: '229400889372',
    projectId: 'zing-mp3-clone-d51e7',
    storageBucket: 'zing-mp3-clone-d51e7.firebasestorage.app',
    iosBundleId: 'com.example.mp3Clone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFnpsETe3FNwJJ-5rqecU33HCdS4VKwI4',
    appId: '1:229400889372:web:aff5795829cfca90ebb7d9',
    messagingSenderId: '229400889372',
    projectId: 'zing-mp3-clone-d51e7',
    authDomain: 'zing-mp3-clone-d51e7.firebaseapp.com',
    storageBucket: 'zing-mp3-clone-d51e7.firebasestorage.app',
    measurementId: 'G-9Y7SZ262QD',
  );
}
