// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVyG1E6g45EgygQ4l7rF9RG2sSNohSZk',
    appId: '1:530993453850:web:868749a21dd0d43f6b2aa3',
    messagingSenderId: '530993453850',
    projectId: 'fir-img-4719c',
    authDomain: 'fir-img-4719c.firebaseapp.com',
    storageBucket: 'fir-img-4719c.appspot.com',
    measurementId: 'G-N62G6J3R8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUBxnnw98lZTKDpf0wq8t-C0bdaYvhjA',
    appId: '1:530993453850:android:539c6fd034ee4ec56b2aa3',
    messagingSenderId: '530993453850',
    projectId: 'fir-img-4719c',
    storageBucket: 'fir-img-4719c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDByBAWlCzqT1f7B1RCxO6VLjMDVryNDXQ',
    appId: '1:229400889372:ios:e6b94a3b55e0d870ebb7d9',
    messagingSenderId: '229400889372',
    projectId: 'zing-mp3-clone-d51e7',
    storageBucket: 'zing-mp3-clone-d51e7.firebasestorage.app',
    iosBundleId: 'com.example.mp3Clone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDByBAWlCzqT1f7B1RCxO6VLjMDVryNDXQ',
    appId: '1:229400889372:ios:e6b94a3b55e0d870ebb7d9',
    messagingSenderId: '229400889372',
    projectId: 'zing-mp3-clone-d51e7',
    storageBucket: 'zing-mp3-clone-d51e7.firebasestorage.app',
    iosBundleId: 'com.example.mp3Clone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz_qc5pPZV9nkZSy6ksmvGRSnITZ7rbY4',
    appId: '1:530993453850:web:cb5fc0d819db9fbf6b2aa3',
    messagingSenderId: '530993453850',
    projectId: 'fir-img-4719c',
    authDomain: 'fir-img-4719c.firebaseapp.com',
    storageBucket: 'fir-img-4719c.appspot.com',
    measurementId: 'G-KN9MJQBC71',
  );

}